### PR TITLE
fix: not all generators ran successfully

### LINKED ISSUE #12: First unit test run failed
```
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading golang.org/x/text v0.3.7
/home/runner/work/tempo-operator/tempo-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: interface conversion: types.Type is *types.Interface, not *types.Named
```

https://github.com/os-observability/tempo-operator/runs/8304372293?check_suite_focus=true#step:4:38

### LINKED ISSUE #13: Tempo Operator build fails: not all generators ran successfully
## Issue description
The build of the Tempo Operator fails with the error:
```sh
/home/iblancas/gopath/src/github.com/tempo-operator/api/v1alpha1/microservices_types.go:60:2: invalid field type: any
Error: not all generators ran successfully
```

## Steps to reproduce:
```sh
$ make build
test -s /home/iblancas/gopath/src/github.com/tempo-operator/bin/controller-gen || GOBIN=/home/iblancas/gopath/src/github.com/tempo-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2
go: downloading sigs.k8s.io/controller-tools v0.9.2
go: downloading github.com/spf13/cobra v1.4.0
go: downloading golang.org/x/tools v0.1.10-0.20220218145154-897bd77cd717
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/fatih/color v1.12.0
go: downloading github.com/gobuffalo/flect v0.2.5
go: downloading k8s.io/apiextensions-apiserver v0.24.0
go: downloading k8s.io/api v0.24.0
go: downloading k8s.io/apimachinery v0.24.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go: downloading sigs.k8s.io/yaml v1.3.0
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading k8s.io/utils v0.0.0-20220210201930-3a6ce19ff2f9
go: downloading k8s.io/klog/v2 v2.60.1
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.2.1
go: downloading github.com/google/gofuzz v1.1.0
go: downloading sigs.k8s.io/json v0.0.0-20211208200746-9f7c6b3444d2
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading golang.org/x/sys v0.0.0-20220209214540-3681064d5158
go: downloading github.com/go-logr/logr v1.2.0
go: downloading github.com/json-iterator/go v1.1.12
go: downloading golang.org/x/net v0.0.0-20220127200216-cd36cc0744dd
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/mod v0.6.0-dev.0.20220106191415-9b9b3d81d5e3
go: downloading golang.org/x/text v0.3.7
/home/iblancas/gopath/src/github.com/tempo-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/home/iblancas/gopath/src/github.com/tempo-operator/api/v1alpha1/microservices_types.go:60:2: invalid field type: any
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
```

```sh
$ go version
go version go1.19.1 linux/amd64
```

### PR DESCRIPTION
**Pull request by frzifus**
closes #12 #13

### CODE REVIEW

**Review by iblancasa — APPROVED** [review]

File: api/v1alpha1/microservices_types.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ type MicroservicesSpec struct {
 	// But for production use, tenants should be outsourced into a secret or similar.
 	//
 	// +optional
-	Tenants any `json:"tenants,omitempty"`
+	// Tenants any `json:"tenants,omitempty"`
```
Comment (iblancasa) [inline api/v1alpha1/microservices_types.go:60]: Wouldn't it make more sense to just remove it?

**Comment by frzifus** [comment]
seems there is another issues:
```
Error: /home/runner/work/tempo-operator/tempo-operator/api/v1alpha1/microservices_types.go:186:2: encountered struct field "" without JSON tag in type "TempoQueryFrontendSpec"
```

File: api/v1alpha1/microservices_types.go (hunk 1 above)
Comment (pavolloffay) [inline api/v1alpha1/microservices_types.go:60]: please remove it altogether

**Review by iblancasa — APPROVED** [review]

**Review by pavolloffay — APPROVED** [review]
